"""remove ticket_code

Revision ID: 216bd047dd3e
Revises: 30dd105f22a6
Create Date: 2025-09-26 11:02:22.305437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216bd047dd3e'
down_revision: Union[str, None] = '30dd105f22a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('registrations_ticket_code_key', 'registrations', type_='unique')
    op.drop_column('registrations', 'ticket_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('ticket_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint('registrations_ticket_code_key', 'registrations', ['ticket_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
