"""events

Revision ID: 30dd105f22a6
Revises: 05f7e078dab8
Create Date: 2025-09-26 09:54:39.416517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30dd105f22a6'
down_revision: Union[str, None] = '05f7e078dab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_type', sa.String(length=100), nullable=False))
    op.add_column('events', sa.Column('fees', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'image_url')
    op.drop_column('events', 'fees')
    op.drop_column('events', 'event_type')
    # ### end Alembic commands ###
