"""event registration foreign key conflict

Revision ID: 73b1dabb5d13
Revises: 216bd047dd3e
Create Date: 2025-09-26 18:59:52.025011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b1dabb5d13'
down_revision: Union[str, None] = '216bd047dd3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('registrations_event_id_fkey', 'registrations', type_='foreignkey')
    op.create_foreign_key(None, 'registrations', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.create_foreign_key('registrations_event_id_fkey', 'registrations', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
